id: "random_forest_hpo"
base_config: 'random_forest'
hpo:
  num_samples: 100
  cpu_per_trial: 4
  gpu_per_trial: 0.15
  hpo_algorithm:
    name: 'SkOptSearch'
    params:
      mode: 'max'

model:
  name: "RandomForestClassifier"
  params:
    n_estimators: ['uniform', [5, 1000]]
    criterion: ['choice', [['gini', 'entropy']]]
    max_depth: ['uniform', [1, 100]]
    min_samples_split: ['uniform', [2, 25]]
    min_samples_leaf: ['uniform', [1, 25]]
    max_features: ['choice', [['auto', 'sqrt', 'log2']]]
    max_leaf_nodes: ['uniform', [2, 500]]
    max_samples: ['uniform', [100, 7000]]