id: "tabnet"
env:
  result_dir: 'results'
  solver: 'pytorch_tabular'
  random_seed: 0
  save_preds: True
data:
  name: "coupon_data"
  params:
    data_dir: 'dataset'
    filename: 'coupon_data.csv'

    remove_nans: True

    ordinal_embed: True
    one_hot_embed: False
    ordinal_embedding_columns: ['time', 'expiration', 'age',
                                'education', 'income', 'Bar', 'CoffeeHouse',
                                'CarryAway', 'RestaurantLessThan20', 'Restaurant20To50',
                                'toCoupon']

model:
  name: "TabNetModelConfig"
  params:
    task: 'classification'
    learning_rate: 1e-3

trainer:
  name: 'Trainer'
  params:
    auto_lr_find: True
    batch_size: 1024
    max_epochs: 100
    gpus: 1