id: "xgboost"
env:
  result_dir: 'results'
  random_seed: 0
  save_preds: False
metrics:
  goal_metric: 'F1'
  save_metrics:
    Accuracy: {num_classes: 10, average: 'macro'}
    Precision: {num_classes: 10, average: 'macro'}
    Recall: {num_classes: 10, average: 'macro'}
    F1: {num_classes: 10, average: 'macro'}
data:
  name: "coupon_data"
  params:
    data_dir: 'dataset'

    ordinal_embedding_columns: ['time', 'expiration', 'age',
                                'education', 'income', 'Bar', 'CoffeeHouse',
                                'CarryAway', 'RestaurantLessThan20', 'Restaurant20To50',
                                'toCoupon']
    one_hot_embedding_columns: ['destination', 'passanger', 'weather', 'coupon', 'gender',
                                'maritalStatus', 'occupation']

model:
  name: "XGBClassifier"
  params:
    max_depth: 5